name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        env:
          - NPROC: 2
            MAKEFLAGS: "-j${NPROC}"
            NIMFLAGS: "--parallelBuild:${NPROC}"
        os: [ubuntu-latest, macos-latest]
    
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout nim-dnsdisc
        uses: actions/checkout@v2

      # We need to do this because of how github cache works
      # I am not sure we can move the cache file, so if we do not do this
      # make update breaks because the cached compiler is there where the submodules
      # are meant to go.
      - name: Submodules
        run: git submodule update --init --recursive

      - name: Cache nim
        uses: actions/cache@v1
        with:
          path: vendor/nimbus-build-system/vendor/Nim/bin
          key: ${{ runner.os }}-${{ matrix.env.NPROC }}-nim-${{ hashFiles('.gitmodules') }}

      - name: Run tests
        run: make test
