name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        env:
          - NPROC: 2
            MAKEFLAGS: "-j${NPROC}"
            NIMFLAGS: "--parallelBuild:${NPROC}"
        branch: [version-1-6, version-2-0]
        os: [ubuntu-latest, macos-latest]
    
    name: '${{ matrix.os }} (Nim ${{ matrix.branch }})'
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout nim-dnsdisc
        uses: actions/checkout@v4

      # We need to do this because of how github cache works
      # I am not sure we can move the cache file, so if we do not do this
      # make update breaks because the cached compiler is there where the submodules
      # are meant to go.
      - name: Submodules
        run: git submodule update --init --recursive

      - name: Cache nim
        uses: actions/cache@v1
        with:
          path: vendor/nimbus-build-system/vendor/Nim/bin
          key: ${{ runner.os }}-${{ matrix.env.NPROC }}-nim-${{ hashFiles('.gitmodules') }}

      - name: Build the Nim compiler
        run: |
          curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus-build-system/master/scripts/build_nim.sh
          env MAKE="make -j${NPROC}" CC=gcc NIM_COMMIT=${{ matrix.branch }} bash build_nim.sh nim csources dist/nimble NimBinaries
          echo '${{ github.workspace }}/nim/bin' >> $GITHUB_PATH

      - name: Run tests
        run: |
          nim --version
          make test
